* Components
** Delta Acts
 - Goal states, a set of methods (planboxes) for achieving goal states, and a decision procedure for ordering/prioritizing methods for achieving goals
 - Results ultimately in an action module activating
*** Example - DeltaProx
**** Planbox 0: Does X think that Y is already near Z?
** Planboxes
 - Has preconditions which define whether they can be used at all, or used before/after other planboxes
 - "Unconscious" preconditions - would never occur to you to try them
 - "Uncontrollable" preconditions - cannot be made true by the actor if they are already true
 - "Plantime" preconditions - preconditions evaluated at time of planbox selection (plantime)
 - "Social" preconditions - take into account social dynamics
 - "Contextual" preconditions - ensure that plans do not undo goals already achieved in the pursuit of the final goal
** Sigma States
 - Physical needs which must be satisfied.
 - Unlike delta-acts they are not nested as subgoals of another goal. They arise spontaneously and periodically.
** Action Modules - Create side effects in the world
 - PTRANS
 - MTRANS
 - ATRANS
** Assertion Mechanism
 - Called by action modules - records the fact of an occurance
** Reaction modules
 - Usually knowledge propagation inferences

* Our implementation
** Classes
*** Planbox
 - Preconditions - Triples that must be true
 - action
 - Postconditions
 - Postact
*** Action Module

* TO DO

** TODO Make kaze find food
 - Actors evaluate options and choose strategies when sigma states activate
** TODO Make kaze eat food
** TODO Refactor actor state into something simpler
** TODO Brainstorm actor state based on hierarchy of needs...
 - Actors delegate some state to environment - e.g. an actor in antarctica is cold - modifications should be made for, say, clothing, fur, etc.
** STARTED Start Actor class
*** TODO Has knowledge graph

* Done
** DONE Write tests for Graph class before you write any more damn code
   CLOSED: [2015-11-05 Thu 23:24]

** DONE Fix bug with place names in ptrans not showing up
   CLOSED: [2015-11-05 Thu 23:25]

** DONE Add bread - bread is food
   CLOSED: [2015-11-06 Fri 12:18]
 - Add item class
 - Items have properties in the form of triples?
 - Knowledge graph represents the properties known by actors at simulation init

** DONE Add FindFood delta act
   CLOSED: [2015-11-06 Fri 16:18]


We need to be able to 
- parameterize data to delta acts on instantiation
- have parameterized data passed into planbox INSTANCES from deltas
- decompose delta acts into planboxes
- Figure out how to prioritize/order planboxes when executing a 'strategy' (delta action)
